# Generated by Django 3.0.7 on 2021-09-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('PK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Paper_name', models.CharField(max_length=255, null=True)),
                ('Paper_owner', models.CharField(max_length=255, null=True)),
                ('Paper_rating', models.FloatField(default=0.0, null=True)),
                ('Paper_image', models.CharField(default='default.jpg', max_length=50)),
                ('Paper_type', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
