# Generated by Django 3.0.7 on 2021-09-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0002_auto_20210929_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='likes',
        ),
    ]
