# Generated by Django 3.2.6 on 2021-10-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0003_auto_20210929_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='External_User',
            fields=[
                ('PK_Exuser', models.AutoField(primary_key=True, serialize=False)),
                ('Exuser_type', models.CharField(max_length=100, null=True)),
                ('Exuser_name', models.CharField(max_length=100, null=True)),
                ('Exuser_lastname', models.CharField(max_length=100, null=True)),
                ('Exuser_position', models.CharField(max_length=100, null=True)),
                ('Exuser_Ageny', models.CharField(max_length=100, null=True)),
                ('Exuser_email', models.CharField(max_length=25, null=True)),
                ('Exuser_tel', models.CharField(max_length=12, null=True)),
                ('Exuser_address', models.TextField(null=True)),
                ('Exuser_password', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internal_User',
            fields=[
                ('PK_Inuser', models.AutoField(primary_key=True, serialize=False)),
                ('Inuser_id', models.CharField(max_length=100, null=True)),
                ('Inuser_name', models.CharField(max_length=100, null=True)),
                ('Inuser_lastname', models.CharField(max_length=100, null=True)),
                ('Inuser_position', models.CharField(max_length=100, null=True)),
                ('Inuser_Ageny', models.CharField(max_length=100, null=True)),
                ('Inuser_email', models.CharField(max_length=25, null=True)),
                ('Inuser_tel', models.CharField(max_length=12, null=True)),
                ('Inuser_address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=10, null=True)),
                ('survey_score1', models.IntegerField(default=0, null=True)),
                ('survey_score2', models.IntegerField(default=0, null=True)),
                ('survey_score3', models.IntegerField(default=0, null=True)),
                ('survey_score4', models.IntegerField(default=0, null=True)),
                ('survey_score5', models.IntegerField(default=0, null=True)),
                ('survey_score6', models.IntegerField(default=0, null=True)),
                ('survey_score7', models.IntegerField(default=0, null=True)),
                ('survey_avgscore', models.IntegerField(default=0, null=True)),
                ('survey_comment', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='Paper_PDF',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='Paper_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
