# Generated by Django 3.0.7 on 2021-10-14 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0004_auto_20211011_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Paper_img1',
            field=models.CharField(default='default.jpg', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='Paper_img2',
            field=models.CharField(default='default.jpg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='external_user',
            name='Exuser_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internal_user',
            name='Inuser_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='papers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='peacon_app.Paper'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='survey_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Creater',
            fields=[
                ('PK_Creater', models.AutoField(primary_key=True, serialize=False)),
                ('Creater_type', models.CharField(max_length=100, null=True)),
                ('Creater_name', models.CharField(max_length=100, null=True)),
                ('Creater_lastname', models.CharField(max_length=100, null=True)),
                ('Creater_own', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creater_user', to='peacon_app.Paper')),
            ],
        ),
    ]
