# Generated by Django 3.0.7 on 2021-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0005_auto_20211014_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Paper_reward',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
