# Generated by Django 3.2.6 on 2021-11-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0008_auto_20211116_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
