# Generated by Django 3.0.7 on 2021-11-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0009_auto_20211116_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_do',
            fields=[
                ('PK_listnum', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_lastname', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(max_length=1, null=True)),
                ('user_tel', models.CharField(max_length=12, null=True)),
                ('user_logindate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
