# Generated by Django 3.0.7 on 2021-11-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0010_auto_20211124_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Paper_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Paper_owner',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
