# Generated by Django 3.0.7 on 2021-11-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0011_auto_20211126_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker_user',
            name='Speaker_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speaker_user',
            name='Speaker_line',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
