# Generated by Django 3.0.7 on 2021-11-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0012_auto_20211129_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='survey_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
