# Generated by Django 3.0.7 on 2021-11-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peacon_app', '0013_auto_20211130_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker_user',
            name='Speaker_position',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
